{% set name = "yaqd-lightcon" %}
{% set version = "2021.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c25f2ec7cca89370a5ec08f6b080fe6ac99acfef43aa618dffbbc86ba15fa698

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-lightcon-topas4-motor = yaqd_lightcon._lightcon_topas4_motor:LightconTopas4Motor.main
    - yaqd-lightcon-topas4-shutter = yaqd_lightcon._lightcon_topas4_shutter:LightconTopas4Shutter.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - aiohttp
    - yaqd-core >=2020.10.1
  run:
    - python >=3.7
    - aiohttp
    - yaqd-core >=2020.10.1

test:
  imports:
    - yaqd_lightcon
  commands:
    - pip check
    - yaqd-lightcon-topas4-motor --help
    - yaqd-lightcon-topas4-shutter --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for hardware from Light Conversion
  dev_url: https://gitlab.com/yaq/yaqd-lightcon
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
